
mongodb:
  image: mongo:3.2.9
  env_file: .docker-environment
  ports:
    - "27017:27017"
  volumes:
    - ./data/mongodb:/data/db
    
elasticsearch:
  image: elasticsearch:2.3.5
  env_file: .docker-environment
  ports:
    - "9200:9200"
  volumes:
    - ./data/es:/usr/share/elasticsearch/data

memcached:
  image: memcached:1.4.31
  env_file: .docker-environment
  ports:
    - "11211:11211"
  
app:
  build: .
  ports:
    - "5000:5000"
  links:
    - mongodb
    - memcached
    - elasticsearch
  volumes:
    - .:/usr/src/app
  env_file: .docker-environment
